name: Java Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: 'master'
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: '20.0.1'
          distribution: 'adopt'

      - name: Maven Build
        run: mvn -B package --file pom.xml

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: SpotBugs
        run: mvn spotbugs:check

      - name: Run Tests
        run: mvn test